version: '3.8'

services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    # depends_on:
    #   - blazor-server

  postgres-container:
    image: postgres:latest
    environment:
      POSTGRES_DB: Chinook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "54321:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  # blazor-server:
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./MyApplication/out:/app
  #   depends_on:
  #     - postgres-container
